name: Update Flex endpoint

on:
    push:
        branches:
            - main
    workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
    contents: write

defaults:
    run:
        shell: bash

jobs:
    call-flex-update:
        uses: neuralglitch/symfony-recipes/.github/workflows/callable-flex-update.yml@main
        with:
            versions_json: .github/versions.json
